apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: food-delivery
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8081
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 30005
        hostPort: 30005
        protocol: TCP

  - role: worker
  - role: worker
