apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: food-delivery
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=
  mongo-database: dG9tYXRv
---
apiVersion: v1 
kind: Secret
metadata:
  name: backend-secret
  namespace: food-delivery
type: Opaque
data:
  jwt-secret: eW91cl9zZWNyZXRfa2V5X2hlcmU=
  stripe-secret-key: eW91cl9zdHJpcGVfc2VjcmV0X2tleV9oZXJl